//{{NO_DEPENDENCIES}}
// Microsoft Visual C++ generated include file.
// Used by MakePhotoDisk3.rc
//
#define IDD_ABOUTBOX                    100
#define IDP_OLE_INIT_FAILED             100
#define IDR_MAINFRAME                   128
#define IDR_MakePhotoDisk3TYPE          130
#define IDR_THEME_MENU                  200
#define ID_SET_STYLE                    201
#define ID_VIEW_APPLOOK_WIN_2000        205
#define ID_VIEW_APPLOOK_OFF_XP          206
#define ID_VIEW_APPLOOK_WIN_XP          207
#define ID_VIEW_APPLOOK_OFF_2003        208
#define ID_VIEW_APPLOOK_VS_2005         209
#define ID_VIEW_APPLOOK_VS_2008         210
#define ID_VIEW_APPLOOK_OFF_2007_BLUE   215
#define ID_VIEW_APPLOOK_OFF_2007_BLACK  216
#define ID_VIEW_APPLOOK_OFF_2007_SILVER 217
#define ID_VIEW_APPLOOK_OFF_2007_AQUA   218
#define ID_VIEW_APPLOOK_WINDOWS_7       219
#define IDD_SELECT_CATALOG_COLLECTION   310
#define IDB_COLLECTION_TREE_IMAGES      311
#define IDD_DEFINE_PROJECT              312
#define IDD_CONFIRM_PROJECT_CREATION    314
#define IDB_CAUTION_TAG                 318
#define IDB_NOTE_TAG                    319
#define IDB_STOP_TAG                    320
#define IDB_NO_PREVIEW                  322
#define IDB_OUTDATED_JPEG               323
#define IDD_UPDATE_PROJECT              324
#define IDD_EDIT_OUTPUT_FORM            325
#define IDD_REFRESH_CONTENT             326
#define IDR_HTML1                       327
#define IDR_CONTACT_SHEET               327
#define IDR_PRESENTATION                328
#define IDR_LIGHT_TABLE_RCLICK_SINGLE_SELECT 329
#define IDD_IMAGE_PROPERTIES            330
#define IDB_UPDATE_DONE                 331
#define IDB_UPDATE_CANCELED             332
#define IDB_UPDATE_ERROR                333
#define IDB_PNG1                        334
#define IDB_UPDATE_NUMBER               334
#define IDD_PHOTO_TITLE_EDIT            336
#define IDD_PHOTO_TIME_EDIT             337
#define IDR_LIGHT_TABLE_RCLICK_MULTI_SELECT 338
#define IDD_PHOTO_TITLE_MULTI_XXX       338
#define IDD_PHOTO_TIME_MULTI            338
#define IDD_PHOTO_TITLE_MULTI           339
#define IDD_PHOTOCAM_MULTI              340
#define IDD_PHOTO_COMMENT_MULTI         341
#define IDC_CATALOG_BROWSE              1000
#define IDC_COLLECTION_TREE             1001
#define IDC_CATALOG_COMBO               1002
#define IDC_PROJECT_TYPE_COMBO          1003
#define IDC_NEXT_STEP                   1004
#define IDC_CREATE_DOCUMENT             1005
#define IDC_CREATE_PROJECT              1006
#define IDC_DIRECTORY_NAME              1007
#define IDC_PROJECT_LOCATION            1008
#define IDC_BROWSE_DIRECTORY            1009
#define IDC_DISK_TYPE_DESCRIPTION       1010
#define IDC_CATALOG_NAME                1011
#define IDC_BACK                        1011
#define IDC_COLLECTION_NAME             1012
#define IDC_PHOTO_COUNT                 1013
#define IDC_DISK_TYPE                   1014
#define IDC_UDPATE_FILES                1015
#define IDC_BUTTON2                     1016
#define IDC_BURN_DISK                   1016
#define IDC_COLLECTION_DESCRIPTION      1017
#define IDC_BUTTON3                     1019
#define IDC_EDIT_START_PAGE             1019
#define IDC_CREATED_WITH_CAMERA_ON_DATE 1022
#define IDC_TITLE_AND_DESCRIPTION       1023
#define IDC_EXPOSURE_DATA               1024
#define IDC_CHECK3                      1025
#define IDC_HAS_COMMENT                 1025
#define IDC_EDIT_CAMERA_NAME            1025
#define IDC_PROGRESS1                   1026
#define IDC_PROGRESS_BAR                1026
#define IDC_CURRENT_FILE                1027
#define IDC_PICTURE_FRAME               1028
#define IDC_DISK_USAGE                  1029
#define IDC_FILE_NAME                   1030
#define IDC_PATH                        1031
#define IDC_CREATED_TIME                1032
#define IDC_MODIFIED_TIME               1033
#define IDC_ACCESSED_TIME               1034
#define IDC_FILE_SIZE                   1035
#define IDC_EDIT_KEY_IMAGE              1036
#define IDC_EDIT_DISK_ICON              1037
#define IDC_DISK_TYPE_TEXT              1039
#define IDC_DISK_ICON_PIC               1040
#define IDC_KEY_IMAGE_PIC               1041
#define IDC_DISK_TITLE_EDIT             1042
#define IDC_EDIT2                       1043
#define IDC_DISK_REVISION_EDIT          1043
#define IDC_DESCR_EDIT                  1043
#define IDC_PROGRESS_BAR_CAPTION        1045
#define IDC_ADD_COMMENT                 1046
#define IDC_TITLE_EDIT                  1050
#define IDC_CUSTOM_TITLE_CHECK          1051
#define IDC_CUSTOM_DESCR_CHECK          1052
#define IDC_CREATE_DATE_TIME            1054
#define IDC_OVERWRIDE_CREATE_TIME       1057
#define IDC_HOURS_EDIT                  1058
#define IDC_ADJUST_TIME_CHECK           1059
#define IDC_SPIN1                       1060
#define IDC_SPIN2                       1061
#define IDC_MINUTE_EDIT                 1062
#define IDC_CAMERA_NAME_EDIT            1063
#define IDC_CHECK4                      1064
#define IDC_PHOTOGRAPHER_CREDIT_CHECK   1064
#define IDC_PHOTOGRAPHER_EDIT           1065
#define IDC_EDIT1                       1067
#define IDC_ADJUST_TIME                 1067
#define IDC_EXTENDED_EDIT               1067
#define IDC_CATALOG                     1067
#define IDC_CAPTION_PREVIEW             1068
#define IDC_CHECK1                      1069
#define IDC_ENABLE_EXTENDED_COMMENT     1069
#define IDC_LARGE_PRESENTATION          1069
#define IDC_ADJUST_TIME_EDIT            1070
#define IDC_COMPRESSED                  1070
#define IDC_CUSTOM_PHOTOGRAPHER         1071
#define IDC_CUSTOM_PHOTOG_CHECK         1071
#define IDC_FACEBOOK                    1071
#define IDC_PHOTOG_EDIT                 1072
#define IDC_FULL_SIZE                   1072
#define IDC_CUSTOM_CAMERA_CHECK         1073
#define IDC_CAMERA_EDIT                 1074
#define IDC_COMMENT                     1075
#define IDC_EDIT3                       1076
#define IDC_COLLECTION                  1076
#define IDC_WATERMARK_PRESENTATION      1078
#define IDC_WATERMARK_COMPRESSED        1079
#define IDC_WATERMARK_FACEBOOK          1080
#define IDC_WATERMARK_FULL_SIZE         1081
#define ID_PROPERTIES_EDITSOURCE        32771
#define ID_EDIT_SOURCE                  32772
#define ID_LTRIGHTCLICK_PROPERTIES      32773
#define ID_PROPERTIES                   32774
#define ID_LTRIGHTCLICK_SHOWINEXPLORER  32775
#define ID_SHOW_IN_EXPLORER             32776
#define ID_LTRIGHTCLICK_SELECTKEYIMAGE  32777
#define ID_LTRIGHTCLICK_SELECT          32778
#define ID_SELECT_KEY_IMAGE             32779
#define ID_SELECT_DISK_ICON             32780
#define ID_RECENTFILE_RECENTFILE        32781
#define ID_RECENTFILE_RECENTFILE32782   32782
#define ID_RECENTFILE_RECENTFILE32783   32783
#define ID_RECENTFILE_RECENTFILE32784   32784
#define ID_FILE_MRU_POPUP               32785
#define ID_RECENTFILE_RECENTFILE32786   32786
#define ID_FILE_MRU_FILE10ID_FILE_MRU_FILE1 32787
#define ID_RECENTFILE_RECENTFILE32788   32788
#define ID__SETTITLEDESCRIPTION         32789
#define ID__SETTIMEADJUST               32790
#define ID__SETPHOTOGRAPHER             32791
#define ID__EDITCOMMENT                 32792
#define ID__SETPHOTOGANDCAMERA          32793

// Next default values for new objects
// 
#ifdef APSTUDIO_INVOKED
#ifndef APSTUDIO_READONLY_SYMBOLS
#define _APS_NEXT_RESOURCE_VALUE        339
#define _APS_NEXT_COMMAND_VALUE         32794
#define _APS_NEXT_CONTROL_VALUE         1077
#define _APS_NEXT_SYMED_VALUE           310
#endif
#endif
